-- generated by tools/gen_sfx.py -- do not edit
return {
  jump = {bank=1, first=0, last=1542},
  popcorn = {bank=1, first=1873, last=3636},
  collect_carrot = {bank=1, first=3967, last=5289},
  collect_capsicum = {bank=1, first=5620, last=6942},
  collect_zucchini = {bank=1, first=7273, last=8595},
  collect_powerup = {bank=1, first=8926, last=11571},
  dash = {bank=1, first=12013, last=13335},
  squeak = {bank=1, first=13666, last=17413},
  damage = {bank=1, first=17855, last=20720},
  hawk_screech = {bank=1, first=21162, last=23366},
  water_burst = {bank=1, first=23697, last=27003},
  enemy_defeat = {bank=1, first=27445, last=29208},
  menu_move = {bank=1, first=29539, last=30089},
  menu_select = {bank=1, first=30310, last=31411},
  win_jingle = {bank=2, first=0, last=7937},
  game_over = {bank=2, first=8599, last=15433},
}
