// GENERATED by tools/gen_ca_bundle.py — do not edit.
#pragma once

// 11 PEM root certificates, concatenated, NUL-terminated.
// Regenerate: python3 tools/gen_ca_bundle.py (see its docstring).
extern const char g_ca_bundle_pem[];
extern const unsigned g_ca_bundle_pem_len;  // strlen(g_ca_bundle_pem)
