#pragma once
// Generated by tools/extract_builtin_fonts.py - do not edit.
#include <stdint.h>

#define FONT_6X8_WIDTH  6
#define FONT_6X8_HEIGHT 8
#define FONT_6X8_FIRST  0x20
#define FONT_6X8_LAST   0x7E

// Row-major, MSB = leftmost pixel, 8 bytes per glyph, ASCII 0x20..0x7E.
extern const uint8_t font_6x8[95][8];
