#pragma once
// Generated by tools/extract_builtin_fonts.py - do not edit.
#include <stdint.h>

#define FONT_8X12_WIDTH  8
#define FONT_8X12_HEIGHT 12
#define FONT_8X12_FIRST  0x20
#define FONT_8X12_LAST   0x7E

// Row-major, MSB = leftmost pixel, 12 bytes per glyph, ASCII 0x20..0x7E.
extern const uint8_t font_8x12[95][12];
