#!/usr/bin/env python3
"""Synthesize chiptune SFX + BGM for Guinea Pig Run.
Output: sfx/bank1.wav (+bank2.wav on overflow), sfx/bgm.wav, sfx/sfx_ranges.lua
Deterministic: fixed seed, stdlib wave/math/random only."""
import math, os, random, wave

RATE = 11025
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, "..", "sfx"))
os.makedirs(OUT, exist_ok=True)
rng = random.Random(42)

def osc(kind, f, t):
    ph = (f * t) % 1.0
    if kind == "square": return 1.0 if ph < 0.5 else -1.0
    if kind == "tri":    return 4 * abs(ph - 0.5) - 1.0
    if kind == "sine":   return math.sin(2 * math.pi * ph)
    if kind == "noise":  return rng.uniform(-1, 1)
    raise ValueError(kind)

def layer(kind, f0, f1, dur, vol=0.5, attack=0.005, decay=None, delay=0.0,
          vibrato_hz=0.0, vibrato_depth=0.0):
    """Render one layer; returns (start_frame, [samples])."""
    decay = dur if decay is None else decay
    n = int(dur * RATE)
    out = []
    for i in range(n):
        t = i / RATE
        k = i / max(1, n - 1)
        f = f0 + (f1 - f0) * k
        if vibrato_hz:
            f *= 1 + vibrato_depth * math.sin(2 * math.pi * vibrato_hz * t)
        env = min(1.0, t / attack) if t < attack else max(0.0, 1 - (t - attack) / max(1e-6, decay - attack))
        out.append(vol * env * osc(kind, f, t))
    return int(delay * RATE), out

def mix(layers, total_dur):
    n = int(total_dur * RATE)
    buf = [0.0] * n
    for start, samples in layers:
        for i, s in enumerate(samples):
            if start + i < n:
                buf[start + i] += s
    peak = max(1e-6, max(abs(s) for s in buf))
    gain = 0.89 / peak if peak > 0.89 else 1.0
    return [int(max(-1, min(1, s * gain)) * 32767) for s in buf]

# name -> (total_dur, [layer(...)], gap_after_ms)
EFFECTS = [
    ("jump",         0.14, [layer("square", 300, 700, 0.12, 0.45)], 30),
    ("popcorn",      0.16, [layer("square", 660, 660, 0.06, 0.4),
                            layer("square", 880, 880, 0.06, 0.4, delay=0.07)], 30),
    ("collect_carrot",   0.12, [layer("square", 880, 1320, 0.10, 0.4)], 30),
    ("collect_capsicum", 0.12, [layer("square", 660, 990, 0.10, 0.4)], 30),
    ("collect_zucchini", 0.12, [layer("square", 550, 780, 0.10, 0.4)], 30),
    ("collect_powerup", 0.24, [layer("tri", f, f, 0.055, 0.5, delay=d)
        for d, f in [(0, 523), (0.06, 659), (0.12, 784), (0.18, 1047)]], 40),
    ("dash",         0.12, [layer("noise", 0, 0, 0.09, 0.35),
                            layer("square", 330, 180, 0.10, 0.3)], 30),
    ("squeak",       0.34, [layer("square", 1400, 500, 0.32, 0.45,
                                  vibrato_hz=25, vibrato_depth=0.06)], 40),
    ("damage",       0.26, [layer("square", 220, 110, 0.24, 0.5),
                            layer("noise", 0, 0, 0.10, 0.25)], 40),
    ("hawk_screech", 0.20, [layer("square", 1000, 1600, 0.18, 0.3,
                                  vibrato_hz=40, vibrato_depth=0.08),
                            layer("noise", 0, 0, 0.18, 0.15)], 30),
    ("water_burst",  0.30, [layer("noise", 0, 0, 0.28, 0.4, attack=0.03)], 40),
    ("enemy_defeat", 0.16, [layer("square", 500, 120, 0.14, 0.45),
                            layer("noise", 0, 0, 0.05, 0.3)], 30),
    ("menu_move",    0.05, [layer("square", 800, 800, 0.03, 0.3)], 20),
    ("menu_select",  0.10, [layer("square", 1000, 1400, 0.08, 0.35)], 20),
    ("win_jingle",   0.72, [layer("square", f, f, 0.13, 0.4, delay=d)
        for d, f in [(0, 784), (0.15, 1047), (0.30, 1319), (0.45, 1568)]]
        + [layer("tri", f / 2, f / 2, 0.13, 0.3, delay=d)
        for d, f in [(0, 784), (0.15, 1047), (0.30, 1319), (0.45, 1568)]], 60),
    ("game_over",    0.62, [layer("square", f, f, 0.17, 0.4, delay=d)
        for d, f in [(0, 330), (0.20, 262), (0.40, 220)]], 40),
]

def write_wav(path, samples):
    with wave.open(path, "wb") as w:
        w.setnchannels(1); w.setsampwidth(2); w.setframerate(RATE)
        w.writeframes(b"".join(int(s).to_bytes(2, "little", signed=True)
                               for s in samples))

def main():
    banks = {1: [], 2: []}
    ranges = {}
    for name, dur, layers, gap_ms in EFFECTS:
        smp = mix(layers, dur)
        gap = [0] * int(gap_ms * RATE / 1000)
        bank = 1 if 2 * (len(banks[1]) + len(smp) + len(gap)) <= 65536 else 2
        first = len(banks[bank])
        banks[bank] += smp + gap
        ranges[name] = (bank, first, first + len(smp) - 1)
    for b, data in banks.items():
        assert 2 * len(data) <= 65536, f"bank{b} overflow: {2*len(data)} bytes"
        if data:
            write_wav(os.path.join(OUT, f"bank{b}.wav"), data)
            print(f"bank{b}.wav: {len(data)*2} bytes data")
    with open(os.path.join(OUT, "sfx_ranges.lua"), "w") as f:
        f.write("-- generated by tools/gen_sfx.py -- do not edit\nreturn {\n")
        for name, (bank, first, last) in ranges.items():
            f.write(f'  {name} = {{bank={bank}, first={first}, last={last}}},\n')
        f.write("}\n")

    # BGM: 4-bar loop, I-V-vi-IV in C, square arp + tri bass + noise hats
    BPM, SPB, BARS = 132, 60 / 132, 4
    CHORDS = [(261.6, 329.6, 392.0), (196.0, 246.9, 293.7),
              (220.0, 261.6, 329.6), (174.6, 220.0, 261.6)]
    bar = int(SPB * 4 * RATE)
    bgm = [0.0] * (bar * BARS)
    def add(samples, at):
        for i, s in enumerate(samples):
            if at + i < len(bgm): bgm[at + i] += s
    for b_i, chord in enumerate(CHORDS):
        base = b_i * bar
        for note_i in range(8):                      # 8th-note arpeggio
            f = chord[note_i % 3] * 2
            st, s = layer("square", f, f, SPB / 2 * 0.9, 0.16)
            add(s, base + int(note_i * SPB / 2 * RATE))
        st, s = layer("tri", chord[0] / 2, chord[0] / 2, SPB * 3.6, 0.30)
        add(s, base)
        for hat in range(4):                         # quarter-note hats
            st, s = layer("noise", 0, 0, 0.03, 0.10)
            add(s, base + int(hat * SPB * RATE))
    peak = max(abs(s) for s in bgm)
    bgm16 = [int(s / peak * 0.7 * 32767) for s in bgm]
    write_wav(os.path.join(OUT, "bgm.wav"), bgm16)
    print(f"bgm.wav: {len(bgm16)*2} bytes ({len(bgm16)/RATE:.1f}s)")

if __name__ == "__main__":
    main()
