#!/usr/bin/env python3
"""One-off: lift the 6x8 and 8x12 tables out of src/drivers/display.c into
src/fonts/font_6x8.c and src/fonts/font_8x12.c in the shared pc_font_t
layout (row-major, MSB = leftmost pixel, one byte per row).

The 6x8 source is column-major with LSB = top pixel, so it is rotated.
The 8x12 source is already row-major and is copied verbatim.

Usage: python3 tools/extract_builtin_fonts.py src/drivers/display.c src/fonts
"""
import re
import sys
from pathlib import Path


def parse_table(src: str, name: str, cols: int):
    m = re.search(rf"static const uint8_t {name}\[95\]\[{cols}\] = \{{(.*?)\n\}};", src, re.S)
    if not m:
        sys.exit(f"table {name} not found")
    rows = []
    for line in m.group(1).splitlines():
        nums = re.findall(r"0x[0-9A-Fa-f]+", line.split("//")[0])
        if len(nums) == cols:
            rows.append([int(n, 16) for n in nums])
    if len(rows) != 95:
        sys.exit(f"{name}: expected 95 glyphs, got {len(rows)}")
    return rows


def rotate_6x8(cols6):
    """Column-major (6 bytes, bit n = row n) -> 8 row bytes, MSB = col 0."""
    rows = []
    for r in range(8):
        byte = 0
        for c in range(6):
            if cols6[c] & (1 << r):
                byte |= 0x80 >> c
        rows.append(byte)
    return rows


def emit(path: Path, ident: str, width: int, height: int, glyphs):
    guard = ident.upper()
    h = path.with_suffix(".h")
    h.write_text(
        "#pragma once\n// Generated by tools/extract_builtin_fonts.py - do not edit.\n"
        "#include <stdint.h>\n\n"
        f"#define {guard}_WIDTH  {width}\n#define {guard}_HEIGHT {height}\n"
        f"#define {guard}_FIRST  0x20\n#define {guard}_LAST   0x7E\n\n"
        f"// Row-major, MSB = leftmost pixel, {height} bytes per glyph, ASCII 0x20..0x7E.\n"
        f"extern const uint8_t {ident}[95][{height}];\n"
    )
    lines = [f'#include "{h.name}"\n', "// Generated by tools/extract_builtin_fonts.py - do not edit.\n",
             f"const uint8_t {ident}[95][{height}] = {{\n"]
    for i, g in enumerate(glyphs):
        ch = chr(0x20 + i)
        label = "'\\\\'" if ch == "\\" else f"'{ch}'"
        lines.append("    {" + ",".join(f"0x{b:02X}" for b in g) + f"}}, // {label} (0x{0x20 + i:02X})\n")
    lines.append("};\n")
    path.write_text("".join(lines))


def main():
    src = Path(sys.argv[1]).read_text()
    out = Path(sys.argv[2])
    emit(out / "font_6x8.c", "font_6x8", 6, 8, [rotate_6x8(g) for g in parse_table(src, "s_font6x8", 6)])
    emit(out / "font_8x12.c", "font_8x12", 8, 12, parse_table(src, "s_font8x12", 12))
    print("wrote font_6x8.c/h and font_8x12.c/h")


if __name__ == "__main__":
    main()
