#!/usr/bin/env python3
"""
img_to_c.py — Convert an image to a PicOS splash screen C header.

Usage:
    python tools/img_to_c.py <input_image> [output_header]

Arguments:
    input_image    PNG, JPG, BMP, or any Pillow-supported format
    output_header  Destination .h file (default: src/splash_logo.h)

Requirements:
    pip install pillow

Notes:
    - Images larger than 200×200 are scaled down, preserving aspect ratio.
    - Transparent pixels are composited onto a black background.
    - Output is RGB565 in host byte order, matching the RGB565() macro in display.h.
    - After generating, rebuild with: make -j4 (from the build/ directory).
"""

import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("Error: Pillow is not installed.")
    print("Install it with:  pip install pillow")
    sys.exit(1)

MAX_W = 200
MAX_H = 200


def to_rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def convert(input_path: str, output_path: str) -> None:
    img = Image.open(input_path).convert("RGBA")

    # Scale down if the image exceeds the maximum dimensions
    w, h = img.size
    if w > MAX_W or h > MAX_H:
        ratio = min(MAX_W / w, MAX_H / h)
        w = max(1, int(w * ratio))
        h = max(1, int(h * ratio))
        img = img.resize((w, h), Image.LANCZOS)
        print(f"Resized to {w}×{h}")

    # Convert each pixel to RGB565
    pixels = []
    for y in range(h):
        for x in range(w):
            r, g, b, a = img.getpixel((x, y))
            # Composite transparent pixels onto black
            if a < 255:
                r = (r * a) // 255
                g = (g * a) // 255
                b = (b * a) // 255
            pixels.append(to_rgb565(r, g, b))

    # Write the C header
    source_name = Path(input_path).name
    with open(output_path, "w") as f:
        f.write("#pragma once\n")
        f.write("#include <stdint.h>\n\n")
        f.write("// Auto-generated by tools/img_to_c.py — do not edit manually.\n")
        f.write(f"// Source: {source_name}  ({w}×{h} px, RGB565)\n")
        f.write("//\n")
        f.write("// To regenerate:\n")
        f.write(f"//   python tools/img_to_c.py {source_name} {output_path}\n\n")
        f.write(f"#define LOGO_W {w}\n")
        f.write(f"#define LOGO_H {h}\n\n")
        f.write(f"static const uint16_t logo_data[{w * h}] = {{\n")

        cols_per_line = 8
        for i in range(0, len(pixels), cols_per_line):
            chunk = pixels[i : i + cols_per_line]
            line = "    " + ", ".join(f"0x{p:04X}" for p in chunk)
            if i + cols_per_line < len(pixels):
                line += ","
            f.write(line + "\n")

        f.write("};\n")

    size_bytes = w * h * 2
    print(f"Logo: {w}×{h} px, {size_bytes} bytes ({size_bytes / 1024:.1f} KB flash)")
    print(f"Written → {output_path}")
    print("Rebuild with:  make -j4   (from your build/ directory)")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    input_path = sys.argv[1]
    output_path = sys.argv[2] if len(sys.argv) > 2 else "src/splash_logo.h"

    if not Path(input_path).exists():
        print(f"Error: file not found: {input_path}")
        sys.exit(1)

    convert(input_path, output_path)
