# PNGdec's bundled zlib — alignment-safe copies of inflate.c / inffast.c.
#
# Upstream PNGdec (third_party/PNGdec, a submodule we do not fork) copies
# match bytes with `*(uint32_t *)out = *(uint32_t *)from` whenever
# ALLOWS_UNALIGNED is defined — and it is on both builds: the firmware passes
# -DALLOWS_UNALIGNED=1 (JPEGDEC wants it), and inflate.c/inffast.c define it
# themselves on every 64-bit host. Those pointers are arbitrary byte offsets
# into the output window, so every real PNG performs misaligned 32-bit loads
# and stores: undefined behaviour in C (UBSan aborts the ASan+UBSan simulator
# on any image.load of a PNG) and a strict-aliasing violation besides.
#
# Instead of suppressing the sanitizer, the build compiles patched copies in
# which each of those word copies is a 4-byte memcpy. The compiler lowers a
# constant 4-byte memcpy to a single unaligned LDR/STR on the Cortex-M33
# (armv8-m.main allows unaligned access to Normal memory, which is where the
# PSRAM decode window lives) and to a plain mov on x86-64, so the hot inflate
# loop keeps its word-at-a-time speed — it just stops being UB.
#
# picodeck_pngdec_sources(<out_var> <pngdec_src_dir>) sets <out_var> to the full
# PNGdec source list with inflate.c/inffast.c replaced by the patched copies
# (written under CMAKE_CURRENT_BINARY_DIR/pngdec_aligned; the submodule is
# never modified). The build fails if the upstream text drifts.

function(_picodeck_pngdec_patch _src _dst _expected)
    file(READ "${_src}" _text)
    set(_n 0)
    foreach(_pair
            "*(uint32_t *)out = *(uint32_t *)from;|memcpy(out, from, 4);"
            "*(uint32_t *)put = *(uint32_t *)from;|memcpy(put, from, 4);"
            "pattern = *(uint32_t *)from;|memcpy(&pattern, from, 4);"
            "*(uint32_t *)out = pattern;|memcpy(out, &pattern, 4);"
            "*(uint32_t *)put = pattern;|memcpy(put, &pattern, 4);")
        string(FIND "${_pair}" "|" _bar)
        string(SUBSTRING "${_pair}" 0 ${_bar} _from)
        math(EXPR _to_pos "${_bar} + 1")
        string(SUBSTRING "${_pair}" ${_to_pos} -1 _to)
        set(_before "${_text}")
        string(REPLACE "${_from}" "${_to}" _text "${_text}")
        if(NOT "${_before}" STREQUAL "${_text}")
            # occurrences replaced = length change / per-replacement change
            string(LENGTH "${_before}" _lb)
            string(LENGTH "${_text}" _la)
            string(LENGTH "${_from}" _lf)
            string(LENGTH "${_to}" _lt)
            math(EXPR _k "(${_lb} - ${_la}) / (${_lf} - ${_lt})")
            math(EXPR _n "${_n} + ${_k}")
        endif()
    endforeach()
    string(FIND "${_text}" "(uint32_t *)" _left)
    if(NOT _n EQUAL ${_expected} OR NOT _left EQUAL -1)
        message(FATAL_ERROR
            "picodeck_pngdec: expected ${_expected} unaligned word copies in ${_src}, "
            "patched ${_n} (remaining uint32_t* cast: ${_left}). PNGdec changed — "
            "update cmake/picodeck_pngdec.cmake.")
    endif()
    set(_text "/* PicoDeck: alignment-safe copy generated by cmake/picodeck_pngdec.cmake from\n   ${_src} — do not edit. */\n#include <string.h>\n${_text}")
    # Only rewrite when the content changes, so rebuilds stay incremental.
    if(EXISTS "${_dst}")
        file(READ "${_dst}" _old)
        if("${_old}" STREQUAL "${_text}")
            return()
        endif()
    endif()
    file(WRITE "${_dst}" "${_text}")
endfunction()

function(picodeck_pngdec_sources _out _dir)
    set(_gen "${CMAKE_CURRENT_BINARY_DIR}/pngdec_aligned")
    file(MAKE_DIRECTORY "${_gen}")
    _picodeck_pngdec_patch("${_dir}/inflate.c" "${_gen}/inflate.c" 2)
    _picodeck_pngdec_patch("${_dir}/inffast.c" "${_gen}/inffast.c" 4)
    # Re-run the patch when upstream changes.
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
                 "${_dir}/inflate.c" "${_dir}/inffast.c")
    set(${_out}
        "${_dir}/PNGdec.cpp"
        "${_dir}/adler32.c"
        "${_dir}/crc32.c"
        "${_dir}/infback.c"
        "${_gen}/inffast.c"
        "${_gen}/inflate.c"
        "${_dir}/inftrees.c"
        "${_dir}/zutil.c"
        PARENT_SCOPE)
endfunction()
